language: ruby
rvm:
  - 2.1.5
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rspec
before_script:
  - psql -c 'create database learning_stuff_test' -U postgres